import type { User, Package, Project, Payment, CreditTransaction } from '@/types'

export const MOCK_PACKAGES: Package[] = [
  {
    id: 'pkg_lite',
    name: 'Lite',
    slug: 'lite',
    priceRub: 299,
    credits: 5,
    features: [
      'До 5 обработок',
      'Удаление фона',
      'Улучшение качества',
      '1 формат карточки',
    ],
    recommended: false,
    active: true,
    pricePerCredit: 60,
  },
  {
    id: 'pkg_pro',
    name: 'Pro',
    slug: 'pro',
    priceRub: 699,
    credits: 15,
    features: [
      'До 15 обработок',
      'Удаление фона',
      'Улучшение качества',
      '3 формата карточки',
      '2 обложки',
    ],
    recommended: true,
    active: true,
    pricePerCredit: 47,
  },
  {
    id: 'pkg_ultra',
    name: 'Ultra',
    slug: 'ultra',
    priceRub: 1490,
    credits: 40,
    features: [
      'До 40 обработок',
      'Все функции',
      'Заголовок товара',
      'Описание товара',
      'Premium шаблоны',
    ],
    recommended: false,
    active: true,
    pricePerCredit: 37,
  },
]

export const MOCK_USER: User = {
  id: 'user_demo',
  telegramId: '123456789',
  name: 'Demo User',
  username: 'demo_user',
  avatarUrl: undefined,
  role: 'user',
  credits: 12,
  createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  updatedAt: new Date().toISOString(),
}

export const MOCK_ADMIN: User = {
  id: 'user_admin',
  telegramId: '999999999',
  name: 'Admin',
  username: 'admin_demo',
  avatarUrl: undefined,
  role: 'admin',
  credits: 100,
  createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  updatedAt: new Date().toISOString(),
}

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj_1',
    userId: 'user_demo',
    title: 'Кроссовки Nike Air Max',
    category: 'Одежда и аксессуары',
    sourceImages: ['/demo/product-1.jpg', '/demo/product-2.jpg'],
    selectedOperations: ['remove_bg', 'upscale', 'square_format', 'cover'],
    packageId: 'pkg_pro',
    package: MOCK_PACKAGES[1],
    priceRub: 699,
    status: 'done',
    resultImages: ['/demo/result-1.jpg', '/demo/result-2.jpg', '/demo/result-3.jpg'],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'proj_2',
    userId: 'user_demo',
    title: 'Беспроводные наушники',
    category: 'Электроника',
    sourceImages: ['/demo/product-3.jpg'],
    selectedOperations: ['remove_bg', 'upscale', 'vertical_creative'],
    packageId: 'pkg_lite',
    package: MOCK_PACKAGES[0],
    priceRub: 299,
    status: 'payment_review',
    resultImages: [],
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'proj_3',
    userId: 'user_demo',
    title: 'Керамическая кружка',
    category: 'Дом и сад',
    sourceImages: ['/demo/product-1.jpg'],
    selectedOperations: ['remove_bg', 'square_format'],
    packageId: 'pkg_lite',
    package: MOCK_PACKAGES[0],
    priceRub: 299,
    status: 'draft',
    resultImages: [],
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
]

export const MOCK_PAYMENTS: Payment[] = [
  {
    id: 'pay_1',
    userId: 'user_demo',
    projectId: 'proj_1',
    packageId: 'pkg_pro',
    method: 'manual',
    amountRub: 699,
    starsAmount: 0,
    status: 'paid',
    payerName: 'Иван Иванов',
    payerComment: '1234',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    package: MOCK_PACKAGES[1],
  },
  {
    id: 'pay_2',
    userId: 'user_demo',
    projectId: 'proj_2',
    packageId: 'pkg_lite',
    method: 'manual',
    amountRub: 299,
    starsAmount: 0,
    status: 'needs_review',
    payerName: 'Иван Иванов',
    payerComment: '5678',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    package: MOCK_PACKAGES[0],
    project: MOCK_PROJECTS[1],
    user: MOCK_USER,
  },
]

export const MOCK_TRANSACTIONS: CreditTransaction[] = [
  {
    id: 'tx_1',
    userId: 'user_demo',
    type: 'topup',
    amount: 15,
    reason: 'Пополнение по пакету Pro',
    relatedPaymentId: 'pay_1',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx_2',
    userId: 'user_demo',
    type: 'spend',
    amount: -4,
    reason: 'Обработка проекта: Кроссовки Nike Air Max',
    relatedProjectId: 'proj_1',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx_3',
    userId: 'user_demo',
    type: 'topup',
    amount: 5,
    reason: 'Тестовая оплата (demo)',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
]
